########################
# [{"Feature":{
#              "FeatureName":{
#                             "InputParser":[<Parser Name>,...],
#                             "Key":"KeyString"}
#              ...},
#  "Answer":"Answer Text"},
# ...
# ]
########################
import json
import os
import logging
import time
l = [
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"網路", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"宿舍",
                              },
                 "StudentID": {"InputParser": [
                     "checkDormNetIDUsage"], "Key":"OverUse", },
                 "NetConfig": {"InputParser": [], "Key":"DHCP",
                               },
                 "DormRoom": {"InputParser": ["checkDormNetSwitchHealthy"], "Key":"Alive", }},
     "Answer":"超流量使用"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"網路", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"宿舍",
                              },
                 "StudentID": {"InputParser": [
                     "checkDormNetIDUsage"], "Key":"NoneOverUse", },
                 "NetConfig": {"InputParser": [], "Key":"PPPOE",
                               },
                 "DormRoom": {"InputParser": ["checkDormNetSwitchHealthy"], "Key":"Alive", }},
     "Answer":"請設定為DHCP"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"網路", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"宿舍",
                              },
                 "StudentID": {"InputParser": [
                     "checkDormNetIDUsage"], "Key":"NoneOverUse", },
                 "NetConfig": {"InputParser": [], "Key":"DHCP",
                               },
                 "DormRoom": {"InputParser": ["checkDormNetSwitchHealthy"], "Key":"Dead", }},
     "Answer":"該宿舍目前網路設備維修中"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"網路", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"宿舍",
                              },
                 "StudentID": {"InputParser": [
                     "checkDormNetIDUsage"], "Key":"NoneOverUse", },
                 "NetConfig": {"InputParser": [], "Key":"DHCP",
                               },
                 "DormRoom": {"InputParser": ["checkDormNetSwitchHealthy"], "Key":"Alive", }},
     "Answer":"請聯絡線上客服為您處理"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"網路", },
                 "Location": {"InputParser": [], "Key":"實驗室", }},
     "Answer":"請聯絡貴系網管"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"授權軟體", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"校外",
                              },
                 "ChengKungPortal": {"InputParser": [],
                                     "Key":"成功", },
                 "JupyterInstalled": {"InputParser": [],
                                      "Key":"成功", },
                 "ComputerTimeSet": {"InputParser": [],
                                     "Key":"正常", },
                 "RunAsAdmin": {"InputParser": [], "Key":"是", }},
     "Answer":"請聯絡線上客服為您處理"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"授權軟體", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"校外",
                              },
                 "ChengKungPortal": {"InputParser": [],
                                     "Key":"成功", },
                 "JupyterInstalled": {"InputParser": [],
                                      "Key":"成功", },
                 "ComputerTimeSet": {"InputParser": [],
                                     "Key":"正常", },
                 "RunAsAdmin": {"InputParser": [], "Key":"否", }},
     "Answer":"請以系統管理員身分執行"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"授權軟體", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"校外",
                              },
                 "ChengKungPortal": {"InputParser": [],
                                     "Key":"成功", },
                 "JupyterInstalled": {"InputParser": [],
                                      "Key":"成功", },
                 "ComputerTimeSet": {"InputParser": [],
                                     "Key":"異常", },
                 "RunAsAdmin": {"InputParser": [], "Key":"是", }},
     "Answer":"請進行系統對時"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"授權軟體", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"校外",
                              },
                 "ChengKungPortal": {"InputParser": [],
                                     "Key":"成功", },
                 "JupyterInstalled": {"InputParser": [],
                                      "Key":"失敗", },
                 "ComputerTimeSet": {"InputParser": [],
                                     "Key":"正常", },
                 "RunAsAdmin": {"InputParser": [], "Key":"是", }},
     "Answer":"請安裝VPN軟體Jupyter Notebook"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"授權軟體", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"校外",
                              },
                 "ChengKungPortal": {"InputParser": [],
                                     "Key":"失敗", },
                 "JupyterInstalled": {"InputParser": [],
                                      "Key":"成功", },
                 "ComputerTimeSet": {"InputParser": [],
                                     "Key":"正常", },
                 "RunAsAdmin": {"InputParser": [], "Key":"是", }},
     "Answer":"請確認帳號密碼是否為成功入口帳號密碼"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"授權軟體", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"校內",
                              },
                 "ComputerTimeSet": {"InputParser": [],
                                     "Key":"正常", },
                 "RunAsAdmin": {"InputParser": [], "Key":"是", }},
     "Answer":"請聯絡線上客服為您處理"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"授權軟體", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"校內",
                              },
                 "ComputerTimeSet": {"InputParser": [],
                                     "Key":"異常", },
                 "RunAsAdmin": {"InputParser": [], "Key":"是", }},
     "Answer":"請進行系統對時"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"授權軟體", },
                 "Location": {"InputParser": ["LocationParser"], "Key":"校內",
                              },
                 "ComputerTimeSet": {"InputParser": [],
                                     "Key":"正常", },
                 "RunAsAdmin": {"InputParser": [], "Key":"否", }},
     "Answer":"請以系統管理員身分執行"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"VPN", },
                 "ChengKungPortal": {"InputParser": [],
                                     "Key":"成功", },
                 "JupyterInstalled": {"InputParser": [], "Key":"成功", }},
     "Answer":"請聯絡線上客服為您處理"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"VPN", },
                 "ChengKungPortal": {"InputParser": [],
                                     "Key":"失敗", },
                 "JupyterInstalled": {"InputParser": [], "Key":"成功", }},
        "Answer":"請確認帳號密碼是否為成功入口帳號密碼"},
    {"Feature": {"Keyword": {"InputParser": ["CKIPParser"], "Key":"VPN", },
                 "ChengKungPortal": {"InputParser": [],
                                     "Key":"成功", },
                 "JupyterInstalled": {"InputParser": [], "Key":"失敗", }},
        "Answer":"請安裝VPN軟體Jupyter Notebook"},
]


__PATH__ = os.path.dirname(os.path.abspath(__file__))
with open(__PATH__+"/solution.json", "w",encoding="utf-8") as f:
    json.dump(l, f,ensure_ascii=False)
